function Jac = myfunc_Jac(A_g,L_A,g,n,porosity,q_1,q_2,q_3,rho_1,rho_2)
%MYFUNC_JAC
%    JAC = MYFUNC_JAC(A_G,L_A,G,N,POROSITY,Q_1,Q_2,Q_3,RHO_1,RHO_2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Jul-2018 23:50:27

t2 = 1.0./L_A;
t3 = q_3.^2;
t24 = A_g.*t3.*3.0;
t4 = q_1-t24;
t5 = porosity-1.0;
t6 = 1.0./t5;
t7 = 1.0./q_2;
t8 = rho_1-rho_2;
t14 = q_1.*t7.*t8;
t9 = rho_1-t14;
t10 = 1.0./t9;
t11 = 1.0./q_2.^2;
t12 = q_1.*q_3;
t17 = A_g.*q_3.*t3;
t13 = t12-t17;
t15 = q_1.*t7;
t16 = porosity+t15-1.0;
t18 = 1.0./q_2.^3;
t19 = 1.0./t9.^2;
t20 = t8.^2;
t21 = n.^2;
t22 = sqrt(t3);
t23 = 1.0./q_2.^(4.0./3.0);
Jac = reshape([-q_3.*t2,q_3.*t2.*t6,-t2.*t3.*t6.*t7+q_3.*t2.*t6.*t8.*t10.*t11.*t13+t2.*t3.*t6.*t7.*t8.*t10.*t16+q_3.*t2.*t6.*t11.*t13.*t16.*t19.*t20,0.0,0.0,q_3.*t2.*t6.*t11.*t13+g.*1.0./q_2.^(7.0./3.0).*q_3.*t21.*t22.*(4.0./3.0)-q_1.*q_3.*t2.*t6.*t8.*t10.*t13.*t18-q_3.*t2.*t6.*t8.*t10.*t11.*t13.*t16-q_1.*q_3.*t2.*t6.*t13.*t16.*t18.*t19.*t20,-t2.*t4,t2.*t4.*t6,g.*t21.*t22.*t23.*-2.0-t2.*t6.*t7.*t13-q_3.*t2.*t4.*t6.*t7+t2.*t6.*t7.*t8.*t10.*t13.*t16+q_3.*t2.*t4.*t6.*t7.*t8.*t10.*t16],[3,3]);
